### ISSUE TITLE
[API] 데이터지도_상세보기

### ISSUE THREAD

**Issue by moonyaeyoon** [PINPLE-project/PINPLE-back#10]
## 📝 To-do
- [ ] 프론트에서 마킹된 장소 데이터만 불러올 수 있는지 확인 
- [ ] 혼잡도 전망 출력값 불러오기
- [ ] 인근핀 작성 데이터 불러오기
- [x] 추천장소 데이터 불러오기 

## 💡 Description
설명을 작성하세요.

## ETC
기타사항을 작성하세요.
