### ISSUE TITLE
[API] 데이터지도 1

### ISSUE THREAD

**Issue by moonyaeyoon** [PINPLE-project/PINPLE-back#3]
## 📝 To-do
- [x] 도시 데이터 불러오기
- [x] 도시데이터 json으로 변환하기
- [x] 장소 카테고리 분류
- [ ]  mysql에 저장

## 💡 Description
설명을 작성하세요.

## ETC
기타사항을 작성하세요.
