### ISSUE TITLE
[API] 소셜 회원가입 및 로그인

### ISSUE THREAD

**Issue by kinglim00** [PINPLE-project/PINPLE-back#8]
## 📝 To-do
- [X] 구글 회원가입
- [X] 구글 로그인
- [X] 유효성 검사 추가 및 로컬 DB 테스트
- [x] 카카오 회원가입
- [x] 카카오 로그인
- [x] 구글 JWT 토큰 발급
- [x] 카카오 JWT 토큰 발급
- [x] 구글 회원가입 및 로그인 병합 
- [x] 유효성 검사 추가
- [x] 구글 로그아웃
- [x] 카카오 로그아웃
- [ ] 회원탈퇴

## 💡 Description
소셜 회원가입 및 로그인 API 구현

## ETC
기타사항을 작성하세요.

**Comment by kinglim00** [comment]
userId가 email로 들어가서 각각 email 값을 access Token을 이용하여 받아오는데, 카카오에서 email이 잘 가져와지지 않아 이 부분을 조금 더 찾아봐야 할 것 같습니다 :)

그리고 구글은 회원가입과 로그인 기능이 분리되어 있는데, 카카오는 하나로 진행돼서 추후에 리팩토링 과정을 통해 구글도 로그인과 회원가입을 합치는 과정이 필요할 것으로 보입니다! (→ 구글 로그인 시 DB에 아이디가 없으면 회원가입하는 식)

기본적인 유저 가입 확인만 유효성 검사가 들어가 있는데, 더 필요한 것 같아 이 부분도 추가해놓겠습니다! 

스크랩 기능은 해당 데이터 지도 기능이 머지된 이후에 추가해놓겠습니다.

**Comment by kinglim00** [comment]
회원 탈퇴의 경우, 소셜 측에 access token을 보내서 소셜에도 회원탈퇴를 한다고 요구를 해야하는 것 같은데 따로 세션에는 유저 정보가 저장되고 소셜 access token은 따로 저장하지 않고 있으며, 소셜에서 받은 access token과 refresh token 재발급도 고려해야 하는 것 같아 우선 소셜 측에 요구하지 않고, 저희 db에서 지우는 방식으로 회원 탈퇴를 진행하는 식으로 진행되어야 할 것 같습니다.

이는 소셜 회원탈퇴는 추후에 더 생각해서 고쳐보겠습니다!
